from .fragments import FragmentStateSpace, ResidueStateSpace, PivotSearchParams
from .fragments.pivots import PivotSearchMode
from .annotation import AnnotationParams

# this will be a plaintext configuration file.

SEP = ','

LOSS_NULL_MASS = 0.
LOSS_H2O_MASS = 18.
LOSS_NH3_MASS = 17.
LOSS_CH2N2_MASS = 42.021798072
LOSS_CH2NO_MASS = 44.013638687

LOSS_MASSES = [
    LOSS_NULL_MASS,
    LOSS_H2O_MASS,
    LOSS_NH3_MASS,
    LOSS_CH2N2_MASS,
    LOSS_CH2NO_MASS,
    2. * LOSS_H2O_MASS,
    2. * LOSS_NH3_MASS,
    LOSS_H2O_MASS + LOSS_NH3_MASS]

LOSS_NULL_SYMBOL = ""
LOSS_H2O_SYMBOL = "H2O"
LOSS_NH3_SYMBOL = "NH3"
LOSS_CH2N2_SYMBOL = "CH2N2"
LOSS_CH2NO_SYMBOL = "CH2NO"

LOSS_SYMBOLS = [
    LOSS_NULL_SYMBOL,
    LOSS_H2O_SYMBOL,
    LOSS_NH3_SYMBOL,
    LOSS_CH2N2_SYMBOL,
    LOSS_CH2NO_SYMBOL,
    SEP.join(2 * [LOSS_H2O_SYMBOL]),
    SEP.join(2 * [LOSS_NH3_SYMBOL]),
    SEP.join([LOSS_H2O_SYMBOL] + [LOSS_NH3_SYMBOL])]

CHARGE_1 = 1
CHARGE_2 = 2
CHARGE_3 = 3

FRAGMENT_SPACE = FragmentStateSpace(
    loss_masses = LOSS_MASSES,
    loss_symbols = LOSS_SYMBOLS,
    charges = [
        CHARGE_1, 
        CHARGE_2,
        CHARGE_3,])

AMINO_A_SYMBOL = 'A'
AMINO_R_SYMBOL = 'R'
AMINO_N_SYMBOL = 'N'
AMINO_D_SYMBOL = 'D'
AMINO_C_SYMBOL = 'C'
AMINO_E_SYMBOL = 'E'
AMINO_Q_SYMBOL = 'Q'
AMINO_G_SYMBOL = 'G'
AMINO_H_SYMBOL = 'H'
AMINO_L_SYMBOL = 'L'
AMINO_I_SYMBOL = 'I'
AMINO_K_SYMBOL = 'K'
AMINO_M_SYMBOL = 'M'
AMINO_F_SYMBOL = 'F'
AMINO_P_SYMBOL = 'P'
AMINO_S_SYMBOL = 'S'
AMINO_T_SYMBOL = 'T'
AMINO_W_SYMBOL = 'W'
AMINO_Y_SYMBOL = 'Y'
AMINO_V_SYMBOL = 'V'

AMINO_SYMBOLS = [
    AMINO_A_SYMBOL,
    AMINO_R_SYMBOL,
    AMINO_N_SYMBOL,
    AMINO_D_SYMBOL,
    AMINO_C_SYMBOL,
    AMINO_E_SYMBOL,
    AMINO_Q_SYMBOL,
    AMINO_G_SYMBOL,
    AMINO_H_SYMBOL,
    AMINO_L_SYMBOL,
    AMINO_I_SYMBOL,
    AMINO_K_SYMBOL,
    AMINO_M_SYMBOL,
    AMINO_F_SYMBOL,
    AMINO_P_SYMBOL,
    AMINO_S_SYMBOL,
    AMINO_T_SYMBOL,
    AMINO_W_SYMBOL,
    AMINO_Y_SYMBOL,
    AMINO_V_SYMBOL]

AMINO_A_MONO_MASS = 71.037
AMINO_R_MONO_MASS = 156.10
AMINO_N_MONO_MASS = 114.04
AMINO_D_MONO_MASS = 115.03
AMINO_C_MONO_MASS = 103.01
AMINO_E_MONO_MASS = 129.04
AMINO_Q_MONO_MASS = 128.06
AMINO_G_MONO_MASS = 57.021
AMINO_H_MONO_MASS = 137.06
AMINO_L_MONO_MASS = 113.08
AMINO_I_MONO_MASS = 113.08
AMINO_K_MONO_MASS = 128.10
AMINO_M_MONO_MASS = 131.04
AMINO_F_MONO_MASS = 147.07
AMINO_P_MONO_MASS = 97.053
AMINO_S_MONO_MASS = 87.032
AMINO_T_MONO_MASS = 101.05
AMINO_W_MONO_MASS = 186.08
AMINO_Y_MONO_MASS = 163.06
AMINO_V_MONO_MASS = 99.068

AMINO_MONO_MASSES = [
    AMINO_A_MONO_MASS,
    AMINO_R_MONO_MASS,
    AMINO_N_MONO_MASS,
    AMINO_D_MONO_MASS,
    AMINO_C_MONO_MASS,
    AMINO_E_MONO_MASS,
    AMINO_Q_MONO_MASS,
    AMINO_G_MONO_MASS,
    AMINO_H_MONO_MASS,
    AMINO_L_MONO_MASS,
    AMINO_I_MONO_MASS,
    AMINO_K_MONO_MASS,
    AMINO_M_MONO_MASS,
    AMINO_F_MONO_MASS,
    AMINO_P_MONO_MASS,
    AMINO_S_MONO_MASS,
    AMINO_T_MONO_MASS,
    AMINO_W_MONO_MASS,
    AMINO_Y_MONO_MASS,
    AMINO_V_MONO_MASS]

MOD_NULL_MASS = 0.
MOD_PHOSPHOSERINE_MASS = 97.9769
MOD_METHIONINE_SULFOXIDE_MASS = 15.9949
MOD_METHIONINE_SULFONE_MASS = 31.9898

MODIFICATION_MASSES = [
    MOD_NULL_MASS,
    MOD_PHOSPHOSERINE_MASS,
    MOD_METHIONINE_SULFOXIDE_MASS,
    MOD_METHIONINE_SULFONE_MASS]

MOD_NULL_SYMBOL = ""
MOD_PHOSPHOSERINE_SYMBOL = "SEP"
MOD_METHIONINE_SULFOXIDE_SYMBOL = "MetO"
MOD_METHIONINE_SULFONE_SYMBOL = "MetOne"

MODIFICATION_SYMBOLS = [
    MOD_NULL_SYMBOL,
    MOD_PHOSPHOSERINE_SYMBOL,
    MOD_METHIONINE_SULFOXIDE_SYMBOL,
    MOD_METHIONINE_SULFONE_SYMBOL]

APPLICABLE_MODIFICATIONS = [
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,],
    [0,1,2],
    [0,],
    [0,],
    [0,1],
    [0,],
    [0,],
    [0,],
    [0,]]

MAX_NUM_MODIFICATIONS = 3

MONO_RESIDUE_SPACE = ResidueStateSpace(
    amino_masses = AMINO_MONO_MASSES,
    amino_symbols = AMINO_SYMBOLS,
    modification_masses = MODIFICATION_MASSES,
    modification_symbols = MODIFICATION_SYMBOLS,
    applicable_modifications = APPLICABLE_MODIFICATIONS,
    max_num_modifications = MAX_NUM_MODIFICATIONS)

AMINO_A_AVG_MASS = 71.08
AMINO_R_AVG_MASS = 156.2
AMINO_N_AVG_MASS = 114.1
AMINO_D_AVG_MASS = 115.1
AMINO_C_AVG_MASS = 103.1
AMINO_E_AVG_MASS = 129.1
AMINO_Q_AVG_MASS = 128.1
AMINO_G_AVG_MASS = 57.05
AMINO_H_AVG_MASS = 137.1
AMINO_L_AVG_MASS = 113.2
AMINO_I_AVG_MASS = 113.2
AMINO_K_AVG_MASS = 128.2
AMINO_M_AVG_MASS = 131.2
AMINO_F_AVG_MASS = 147.2
AMINO_P_AVG_MASS = 97.12
AMINO_S_AVG_MASS = 87.08
AMINO_T_AVG_MASS = 101.1
AMINO_W_AVG_MASS = 186.2
AMINO_Y_AVG_MASS = 163.2
AMINO_V_AVG_MASS = 99.13

AMINO_AVG_MASSES = [
    AMINO_A_AVG_MASS,
    AMINO_R_AVG_MASS,
    AMINO_N_AVG_MASS,
    AMINO_D_AVG_MASS,
    AMINO_C_AVG_MASS,
    AMINO_E_AVG_MASS,
    AMINO_Q_AVG_MASS,
    AMINO_G_AVG_MASS,
    AMINO_H_AVG_MASS,
    AMINO_L_AVG_MASS,
    AMINO_I_AVG_MASS,
    AMINO_K_AVG_MASS,
    AMINO_M_AVG_MASS,
    AMINO_F_AVG_MASS,
    AMINO_P_AVG_MASS,
    AMINO_S_AVG_MASS,
    AMINO_T_AVG_MASS,
    AMINO_W_AVG_MASS,
    AMINO_Y_AVG_MASS,
    AMINO_V_AVG_MASS]

AVG_RESIDUE_SPACE = ResidueStateSpace(
    amino_masses = AMINO_AVG_MASSES,
    amino_symbols = AMINO_SYMBOLS,
    modification_masses = MODIFICATION_MASSES,
    modification_symbols = MODIFICATION_SYMBOLS,
    applicable_modifications = APPLICABLE_MODIFICATIONS,
    max_num_modifications = MAX_NUM_MODIFICATIONS)

FRAGMENT_SEARCH_TOLERANCE = 0.01

PIVOT_SEARCH_TOLERANCE = 0.02

OVERLAP_PIVOT_SEARCH = PivotSearchParams(
    tolerance = PIVOT_SEARCH_TOLERANCE,
    mode = PivotSearchMode.OVERLAP)

VIRTUAL_PIVOT_SEARCH = PivotSearchParams(
    tolerance = PIVOT_SEARCH_TOLERANCE,
    mode = PivotSearchMode.VIRTUAL)

PIVOT_SYMMETRY_TOLERANCE = 0.01
PIVOT_SCORE_THRESHOLD_FACTOR = 1.

MONO_ANNOTATION_PARAMS = AnnotationParams(
    fragment_search_tolerance = FRAGMENT_SEARCH_TOLERANCE,
    fragment_state_space = FRAGMENT_SPACE,
    residue_state_space = MONO_RESIDUE_SPACE,
    pivot_search_strategies = [
        OVERLAP_PIVOT_SEARCH, VIRTUAL_PIVOT_SEARCH],
    pivot_symmetry_tolerance = PIVOT_SYMMETRY_TOLERANCE,
    pivot_score_threshold_factor = PIVOT_SCORE_THRESHOLD_FACTOR)

AVG_ANNOTATION_PARAMS = AnnotationParams(
    fragment_search_tolerance = FRAGMENT_SEARCH_TOLERANCE,
    fragment_state_space = FRAGMENT_SPACE,
    residue_state_space = AVG_RESIDUE_SPACE,
    pivot_search_strategies = [
        OVERLAP_PIVOT_SEARCH, VIRTUAL_PIVOT_SEARCH],
    pivot_symmetry_tolerance = PIVOT_SYMMETRY_TOLERANCE,
    pivot_score_threshold_factor = PIVOT_SCORE_THRESHOLD_FACTOR)

VALIDATION_PEPTIDES = ["NREQSTK",
    "AEEHANR","GNAGGLHHHR","HHVLHHQTVDK","HHVLHHQTVDK",
    "HHSTIPQK","FTHQHKPDER","FTHQHKPDER","CEACPKPGTHAHK",
    "HHTIAHYK","KPGVHQPQR","AAHLAAHEAAK","GHSCYRPR",
    "HHNIIR","HLAEHEVK","HGLTNTASHTR","INPDNHNEK",
    "HGATVVNHVK","HLNGHGSPPATNSSHR","HASNIHVEK","ELHVHPK"]
