import pathlib, tempfile
from typing import Iterator, Iterable, Union

from pylibsufr import read_sequence_file, SufrBuilderArgs, SuffixArray as SufrSuffixArray, SufrMetadata, ListOptions, CountOptions, CountResult, BisectOptions, BisectResult

class SuffixArray:
    """Wraps a `pylibsufr.SuffixArray` object, itself a binding to the `SuffixArray` struct in the `libsufr` Rust crate. Only the `write`, `read`, `create`, `bisect`, and `count` methods are implemented."""
    def __init__(self,
        suffix_array: SufrSuffixArray,
        path_to_suffix_array: str,
    ):
        self._suffix_array = suffix_array
        self._path = path_to_suffix_array
        self.query_low_memory = False
        self.max_query_len = None

    def _list(self, 
        ranks = [],
        show_rank = False,
        show_suffix = False,
        show_lcp = False,
        len = None,
        number = None,
    ) -> str:
        tmp = tempfile.NamedTemporaryFile() # create a temp file
        opts = ListOptions(
            ranks = ranks,
            show_rank = show_rank,
            show_suffix = show_suffix,
            show_lcp = show_lcp,
            len = len,
            number = number,
            output = tmp.name,
        )
        result = "If you're seeing this, something broke."
        try:
            self._suffix_array.list(opts)   # output the list to the temp
            with open(tmp.name, 'r') as f:
                result = f.read()
        finally:
            tmp.close()                     # delete the temp
        return result

    def __repr__(self):
        return self._list(
            show_rank = True,
            show_suffix = True,
            show_lcp = True,
        )

    @staticmethod
    def _builder_args(
        path_to_fasta: str,
        path_to_suffix_array: str = None,
        low_memory = False
    ):
        if path_to_suffix_array == None:
            # if an output path wasn't passed, name the suffix array file after the fasta file.
            fasta_stem = pathlib.Path(path_to_fasta).stem
            path_to_suffix_array = f"./{fasta_stem}.sufr"
        # read the fasta into libsufr's internal representation.
        sequence_file_data = read_sequence_file(path_to_fasta)   
        seq_str = ''.join(c for c in sequence_file_data.seq().decode())
        # construct the arguments
        sufr_builder_args = SufrBuilderArgs(
            seq_str.encode(),
            path_to_suffix_array,
            sequence_file_data.start_positions(),
            sequence_file_data.sequence_names(),
            is_dna = False,
            low_memory = low_memory,
        )
        return sufr_builder_args, path_to_suffix_array

    @classmethod
    def write(cls,
        path_to_fasta: str,
        path_to_suffix_array: str = None,
        low_memory = False,
    ):
        """Given path_to_fasta, construct a suffix array from the fasta and write it to a similarly-named .sufr file. If path_to_suffix_array is passed, that value will be used instead of the autogenerated name."""
        sufr_builder_args, path_to_suffix_array = cls._builder_args(path_to_fasta, path_to_suffix_array, low_memory = low_memory)
        return SufrSuffixArray.write(sufr_builder_args)

    @classmethod
    def read(cls,
        path_to_suffix_array: str,
        low_memory = False,
    ):
        """Read a suffix array from its file."""
        return cls(
            SufrSuffixArray.read(path_to_suffix_array, low_memory),
            path_to_suffix_array)

    @classmethod
    def create(cls, 
        path_to_fasta: str, 
        path_to_suffix_array: str = None, 
        low_memory = False,
    ):
        """Create a suffix array from fasta records. 
        If no output path is given, the suffix array 
        file will be named after the input fasta file."""
        sufr_builder_args, path_to_suffix_array = cls._builder_args(path_to_fasta, path_to_suffix_array, low_memory = low_memory)
        return cls(
            SufrSuffixArray(sufr_builder_args),
            path_to_suffix_array)

    def list_suffixes(self,
        ranks: Iterable[int],
        lengths: Iterable[int],
    ) -> list[str]:
        """Given iterables of suffix ranks and lengths, return the corresponding sequences in the suffix array.
        Note: the libsufr interface takes a single length argument, which is set to the max of the lengths iterable. Every suffix is returned with this max length and only afterwards trimmed to its expected length. If your desired set of suffixes contains a diversity of very short and very long sequences, it may be more performant to segment the query into two queries based on length and make two calls to list_suffixes."""
        res = self._list(
            ranks = ranks,
            len = max(lengths),
        )
        res_lines = res.split('\n')
        return [x[:l] for (x,l) in zip(res_lines,lengths)]

    def list_bisect(self,
        results: Iterable[BisectResult],
    ) -> list[str]:
        """Given a list of BisectResult objects, parametize a call to list_suffixes to generate every sequence included in the results."""
        return self.list_suffixes(
            ranks = [x.first_position for x in results],
            lengths = [x.lcp for x in results],
        )
    
    def count(self, 
        queries: Iterable[str],
    ) -> list[int]:
        """Given an iterable of strings, return a list of the same size 
        counting the occurrences of each query in the suffix array."""
        count_options = CountOptions(
            queries = list(queries),
            max_query_len = self.max_query_len,
            low_memory = self.query_low_memory)
        count_results = self._suffix_array.count(count_options)
        return [res.count for res in count_results]
    
    def bisect(self, 
        queries: Iterable[str], 
        prefix: Union[BisectResult,list[BisectResult]] = None,
    ) -> list[BisectResult]:
        """Given an iterable of character queries ( := single-element strings,) and an optional prefix result, count the occurrences of the query strings. If a prefix result is passed, search is restricted to the range of the prefix. Unlike count, this function returns its result type, BisectResult. The occurrence quantities can be accessed via the `count` field of the BisectResult object."""
        if not(all(len(x) == 1 for x in queries)):
            raise ValueError("The `queries` arg contained a non-char str type! All queries must be length one strings.")
        try:
            # is this really faster than 'isinstance'?
            pfx_iter = iter(prefix)
            results = (
                self._suffix_array.bisect(BisectOptions(
                    queries = queries,
                    max_query_len = self.max_query_len,
                    low_memory = self.query_low_memory,
                    prefix_result = x,
                )) for x in pfx_iter
            )
            return sum(results,[])
        except TypeError:
            return self._suffix_array.bisect(BisectOptions(
                queries = queries,
                max_query_len = self.max_query_len,
                low_memory = self.query_low_memory,
                prefix_result = prefix,
            ))
